# Generated by Django 4.2.16 on 2024-10-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User_registration',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='user_details',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='gender',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanagement_app.category'),
            preserve_default=False,
        ),
    ]
