# Generated by Django 4.2.16 on 2025-01-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0002_category_delete_user_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='users',
            field=models.ManyToManyField(blank=True, to='usermanagement_app.user_details'),
        ),
    ]
