# Generated by Django 4.2.16 on 2025-01-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0003_alter_broadcast_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement_app.category'),
        ),
    ]
