# Generated by Django 4.2.16 on 2025-01-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0004_broadcast_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='category',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='category',
            field=models.ManyToManyField(blank=True, to='usermanagement_app.category'),
        ),
    ]
