# Generated by Django 4.2.16 on 2025-03-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0006_user_details_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='goal',
            field=models.TextField(),
        ),
    ]
