# Generated by Django 4.2.16 on 2025-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0007_alter_user_details_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='any_concerns',
            field=models.TextField(blank=True, help_text='Any health or other concerns', null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='any_physical_limitations',
            field=models.TextField(blank=True, help_text='Description of any physical limitations', null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='blood_test',
            field=models.CharField(blank=True, help_text='Blood test results or type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='body_fatpercentage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body fat percentage (e.g., 22.5)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='body_type',
            field=models.CharField(blank=True, help_text='E.g., ectomorph, mesomorph, endomorph', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='bone_density',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bone density measurement', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='date_of_joining',
            field=models.DateField(blank=True, help_text='Date when the person joined', null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters (e.g., 175.50)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Muscle mass in kilograms', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms (e.g., 70.50)', max_digits=5, null=True),
        ),
    ]
