# Generated by Django 4.2.16 on 2025-03-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0008_user_details_any_concerns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='how_did_you_learn_about_us',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='type_of_challange',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
