# Generated by Django 4.2.16 on 2025-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0009_alter_user_details_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='gender',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
