# Generated by Django 4.2.16 on 2025-03-24 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement_app', '0010_alter_user_details_age_alter_user_details_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_activity', models.DateField()),
                ('day_count', models.IntegerField(blank=True, null=True)),
                ('step_count', models.IntegerField(blank=True, null=True)),
                ('diet', models.JSONField(blank=True)),
                ('Exercises', models.TextField(blank=True)),
                ('water_in_liters', models.FloatField(blank=True)),
                ('hours_of_sleep', models.TimeField(blank=True)),
                ('workout_duration', models.TimeField(blank=True)),
                ('calories_initial', models.FloatField(blank=True)),
                ('calories_burn', models.FloatField(blank=True)),
                ('just_relief_activity', models.CharField(blank=True, max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement_app.category')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
