# Generated by Django 4.2.16 on 2025-03-25 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0011_user_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Total_attendance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Total_step_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Total_water_intake',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Total_workout_duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
