# Generated by Django 4.2.16 on 2025-03-25 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement_app', '0012_user_details_total_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tracking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
