# Generated by Django 4.2.16 on 2025-03-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0013_alter_user_tracking_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Total_workout_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
