# Generated by Django 4.2.16 on 2025-03-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0014_alter_user_details_total_workout_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Total_workout_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
