# Generated by Django 4.2.16 on 2025-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0015_alter_user_details_total_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
