# Generated by Django 4.2.16 on 2025-05-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_app', '0016_user_details_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tracking',
            name='workout_duration',
            field=models.DurationField(blank=True),
        ),
    ]
